version: 2.1
jobs:
  build:
    docker:
      - image: graphblas/pygraphblas-minimal:latest
    steps:
      - checkout
      - run:
          name: Install requirements
          command: pip3 install -r requirements.txt
      - run:
          name: Testing install all right
          command: python3 main.py

workflows:
  some_workflow:
    # Run the welcome/run job in its own container
    jobs:
      - build