version: 2.1
jobs:
  build:
    docker:
      - image: graphblas/pygraphblas-minimal:latest
    steps:
      - checkout
      - run:
          name: Install requirements
          command: pip3 install -r requirements.txt
      - run:
          name: Install cfpq_data_devtools
          command: cd deps/CFPQ_Data && python3 setup.py install
      - run:
          name: Run tests
          command: python3 main.py

workflows:
  some_workflow:
    jobs:
      - build